# hostname (and path) to the root
baseURL: "https://gomakethings.com"

# Customer parameters
params:
  description: "A simpler, more resilient way to make things for the web."
  api: "https://gomakethings.com/api/data.json"
  mcSubs: "https://gomakethings.com/checkout/wp-json/gmt-mailchimp/v1/count?round=100&category=3b3060e0f6&id=aaf6f8b9a3"
  font: "https://fonts.googleapis.com/css?family=PT+Serif:400,400i,700,700i"
  rssURL:
    main: "https://gomakethings.com/feed/index.xml"
    notes: "https://gomakethings.com/feed/notes.xml"
    links: "https://gomakethings.com/feed/links.xml"
  rssLimit: 7
  studentURL: "https://courses.gomakethings.com"
  minify: true

# Caches
caches:
  getjson:
    maxAge: "5m"

# The language code for the site
languageCode: "en-us"

# Site title
title: "Go Make Things"

# theme to use (located by default in /themes/THEMENAME/)
theme: "gmt"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/
  notes: /:title/
  events: /:filename/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: ["/content/articles/_2018-01-19-title.md", "/content/articles/_drafts/.*"]

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Markdown Options
blackfriday:
  fractions: false

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true